# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jim McGaw's Blog
email: jpmcgaw@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hiya. I'm an open-source web engineer who likes to write.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.jimmcgaw.com" # the base hostname & protocol for your site
twitter_username: Jim_McGaw
github_username:  jimmcgaw
gems: [jekyll-paginate]


# Build settings
markdown: kramdown
paginate: 10
